export const columns = [
  { name: 'name', label: 'Name', field: 'name', sortable: true, align: 'left' },
  { name: 'legalName', label: 'Legal Name', field: 'legalName', sortable: true, align: 'left' },
  { name: 'country', label: 'Country', field: 'country', sortable: true, align: 'left' },
  {
    name: 'active',
    label: 'Active',
    field: 'active',
    sortable: true,
    align: 'left',
    format: (val) => (val ? '✅' : '❌'),
  },
  {
    name: 'providesAiServices',
    label: 'AI Services',
    field: 'providesAiServices',
    sortable: true,
    align: 'left',
    format: (val) => (val ? '✅' : '❌'),
  },
  {
    name: 'isDpfFound',
    label: 'DPF Found',
    field: 'isDpfFound',
    sortable: true,
    align: 'left',
    format: (val) => (val ? '✅' : '❌'),
  },
  {
    name: 'dateAdded',
    label: 'Date Added',
    field: 'dateAdded',
    sortable: true,
    align: 'left',
    format: (val) => new Date(val).toLocaleDateString(),
  },
  { name: 'parentId', label: 'Parent ID', field: 'parentId', align: 'left' },
]
